src/src/Entity/Shop.php
<?php

namespace App\Entity;

use App\Repository\ShopRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ShopRepository::class)
 */
class Shop
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $link;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

	public function getEmoji(): string
	{
		return explode(' ', $this->getName())[0];
	}

	public function getTextName(): string
	{
		return explode(' ', $this->getName())[1];
	}
}

src/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fio;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="organizer")
     */
    private $orders;

    /**
     * @ORM\OneToMany(targetEntity=OrderItem::class, mappedBy="user", orphanRemoval=true)
     */
    private $orderItems;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->orderItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFio(): ?string
    {
        return $this->fio;
    }

    public function setFio(string $fio): self
    {
        $this->fio = $fio;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setOrganizer($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->contains($order)) {
            $this->orders->removeElement($order);
            // set the owning side to null (unless already changed)
            if ($order->getOrganizer() === $this) {
                $order->setOrganizer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|OrderItem[]
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

	public function getAvatarUrl(): string
	{
		return 'https://randomuser.me/api/portraits/men/' . ($this->getId() % 10 + 1) . '.jpg';
	}

	public function addOrderItem(OrderItem $orderItem): self
	{
		if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems[] = $orderItem;
            $orderItem->setUser($this);
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): self
    {
        if ($this->orderItems->contains($orderItem)) {
            $this->orderItems->removeElement($orderItem);
            // set the owning side to null (unless already changed)
            if ($orderItem->getUser() === $this) {
                $orderItem->setUser(null);
            }
        }

        return $this;
    }
}

src/templates/add-order-item.html.twig
{% extends "base.html.twig" %}

{% block body %}
<form class="add-order-form" method="POST" enctype="multipart/form-data">
    <h3>Добавить позицию в заказ №{{ order.id }}</h3>
    <div class="add-order-form__content">
        <label class="form-label" for="name">
            Название
        </label>
        <input id="name" name="name" type="text" class="form-input add-order-form__input"/>

        <label class="form-label" for="price">
            Стоимость
        </label>
        <input id="price" name="price" type="number" class="form-input add-order-form__input"/>

        <label class="form-label" for="link">
            Ссылка на товар
        </label>
        <input id="link" name="link" type="text" class="form-input add-order-form__input"/>

        <label class="form-label" for="amount">
            Количество
        </label>
        <input id="amount" name="amount" type="number" class="form-input add-order-form__input"/>
    </div>

    <div class="add-order-form__footer">
        <a href="{{ path('order', {id: order.id}) }}" class="form-button">Отменить</a>
        <button class="form-button" type="submit">Добавить</button>
    </div>
</form>
{% endblock body %}

src/templates/add-order.html.twig
{% extends "base.html.twig" %}

{% block body %}
<form class="add-order-form" method="POST" enctype="multipart/form-data">
    <h2>Создание совместного заказа</h2>
    <div class="add-order-form__content">
        <label class="form-label" for="name">
            Название
        </label>
        <input id="name" name="name" type="text" class="form-input add-order-form__input"/>

        <label class="form-label" for="description">
            Описание
        </label>
        <textarea id="description" name="description" type="text" class="form-input default-textarea add-order-form__input"></textarea>

        <label class="form-label" for="address">
            Откуда забрать
        </label>
        <input id="pickup-address" name="pickup-address" type="text" class="form-input add-order-form__input"/>

        <label class="form-label" for="delivery-price">
            Стоимость доставки
        </label>
        <input id="delivery-price" name="delivery-price" type="number" class="form-input add-order-form__input"/>

        <label class="form-label" for="reward">
            Награда
        </label>
        <input id="reward" name="reward" type="number" class="form-input add-order-form__input"/>

        <div class="add-order-form__header">
            Условия завершения заказа
        </div>
        <div class="add-order-form__radio-group">
            <input id="criteria-1" name="condition" type="radio" class="default-radio" value="1">
            <label for="criteria-1" class="form-radio-label">Количество участников</label>
        </div>
        <input type="text" class="form-input add-order-form__applicants-count" placeholder="Сколько участников">
        <div class="add-order-form__radio-group">
            <input id="criteria-2" name="condition" type="radio" class="default-radio" value="2">
            <label for="criteria-2" class="form-radio-label">Общая стоимость</label>
        </div>
        <div class="add-order-form__radio-group">
            <input id="criteria-3" name="condition" type="radio" class="default-radio" value="3">
            <label for="criteria-3" class="form-radio-label">Срок</label>
        </div>
    </div>

    <div class="add-order-form__footer">
        <a href="{{ path('orders') }}" class="form-button">Назад</a>
        <button class="form-button" type="submit">Подтвердить</button>
    </div>
</form>
{% endblock body %}

src/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="/static/common.css">
        <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <script src="/static/common.js"></script>
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
    <div class="mobile-container">
        <div class="fast-login">
            <h3>Войти под:</h3>
            <br>
            {% for user in get_all_users() %}
                <div>
                    <a href="{{ path('admin_login', {'userId': user.id}) }}" class="icon-block">
                        <img class="icon-block__avatar" src="{{ user.avatarUrl }}" alt="">
                        <div>{{ user.fio }} <span style="color:white">{% if user.id == get_current_user().id %} (вы под ним) {% endif %}</span></div>
                    </a>
                    <br>
                </div>
            {% endfor %}
        </div>

        <div class="mobile-container-inner">
            {% block body %}{% endblock %}
        </div>
        </div>
        {% block javascripts %}{% endblock %}
    </body>
</html>

src/templates/index.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <a href="{{ path('orders') }}">
        <img src="/krasivaya-kartinka.jpg" style="margin-left: -8px;" alt="">
    </a>
{% endblock body %}

src/templates/order-list.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="orders">
        <div class="orders__navigation">
            <img src="{{ get_current_user() ? get_current_user().getAvatarUrl() : '' }}" class="avatars-group__item" alt="">
            <div class="orders__navigation-login">{{ get_current_user() ? get_current_user().getFio() : '' }}</div>
            <a href="" class="orders__navigation-icon"><img src="/filter.svg" alt=""></a>
            <a href="{{ path('shop-list') }}" class="orders__navigation-icon orders__navigation-plus-icon"><img src="/plus.svg" alt=""></a>
        </div>
        <div>
            {% for order in orders %}
                <a href="{{ path('order', {id: order.id}) }}" class="order box-layout">
                    <div class="order__header">
                        {{ order.shop.name }}
                        {% if order.getOrderUsers|length == maxOrderCount %}
                            <div class="order-status order-status_payment">Сбор денег</div>
                        {% else %}
                            <div class="order-status order-status_assembly">Формирование</div>
                        {% endif %}
                    </div>
                    <div class="order__description">{{ order.description }}</div>
                    <div class="order__footer order-user-info">
                        <div>
                            <div class="order__applicants-header">Участвуют</div>
                            <div class="avatars-group">
                                {% for user in order.getOrderUsers %}
                                    <img src="{{ user.getAvatarUrl }}" class="avatars-group__item" alt="">
                                {% endfor %}
                            </div>
                            <div class="progress-bar"></div>
                            <div class="order__applicants-count">{{ order.getOrderUsers|length }} участников из {{ maxOrderCount }}</div>
                        </div>
                        <div class="order__footer-right">
                            <div class="order__applicants-header">Стоимость участия</div>
                            <div class="order__applicants-price">
                                <div class="order__applicants-old-price">
                                    {{ order.getDeliveryPrice + order.getOrganizerReward }} ₽
                                </div>
                                <div class="order__applicants-new-price">
                                    {{ order.getParticipationPrice }} ₽
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
        <div class="orders-footer">
            {% set is_my_orders = app.request.get('_route') == 'my_orders' %}

            <a href="{{ path('orders') }}">
                <img class="orders-footer__image" src="/order-list{{ is_my_orders ? '' : '-selected' }}.svg" alt="Список заказов">
            </a>
            <a href="{{ path('my_orders') }}">
                <img class="orders-footer__image" src="/shopping-bag{{ is_my_orders ? '-selected' : '' }}.svg" alt="Мои заказы">
            </a>
            <a href="">
                <img class="orders-footer__image" src="/message-circle.svg" alt="Сообщения">
            </a>
        </div>
    </div>
{% endblock body %}

src/templates/order.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="order-page-grid">
        <h2 class="order-header">
            <a href="{{ path('orders') }}"><img src="/arrow-left.svg" alt=""></a>
            Заказ
        </h2>

        <div class="order-information-grid">
            <div>
                <div class="label-micro-info">Описание</div>
                <div>{{ order.description }}</div>
            </div>
            <div>
                <div class="label-micro-info">Откуда забрать</div>
                <div>{{ order.pickupAddress }}</div>
            </div>

            <div>
                <div class="label-micro-info">Общая стоимость доставки</div>
                <div>{{ order.deliveryPrice }} ₽</div>
            </div>

            <div>
                <div class="label-micro-info">Награда организатору</div>
                <div>{{ order.organizerReward }} ₽</div>
            </div>

            <div>
                <div class="label-micro-info">Участников уже</div>
                <div>
                    {{ memberCount }} из {{ maxOrderCount }}
                    {% if maxOrderCount == memberCount %} <span class="order-complete-label">Собран!</span> {% endif %}
                </div>
            </div>
            <div>
                <div class="label-micro-info">Стоимость участия</div>
                <div>{{ order.getParticipationPrice }} ₽</div>
            </div>
        </div>

        <div class="order-user-info">
            <div>
                <div class="order__applicants-header">Участвуют</div>
                <div class="avatars-group">
                    {% for user in order.getOrderUsers %}
                        <img src="{{ user.getAvatarUrl }}" class="avatars-group__item" alt="">
                    {% endfor %}
                </div>
                <div class="progress-bar"></div>
                <div class="order__applicants-count">{{ memberCount }} участников из {{ maxOrderCount }}</div>
            </div>
            <div class="order__footer-right">
                <div class="order__applicants-header">Стоимость участия</div>
                <div class="order__applicants-price">
                    <div class="order__applicants-old-price">
                        {{ order.getDeliveryPrice + order.getOrganizerReward }} ₽
                    </div>
                    <div class="order__applicants-new-price">
                        {{ order.getParticipationPrice }} ₽
                    </div>
                </div>
            </div>
        </div>

        <div>
            <div class="micro-title">Статус</div>
            <div class="order-status order-status_assembly" style="display: inline-block;">Формирование</div>
        </div>

        <div class="box-layout" style="display: flex;">
            <div class="shop-title-info">
                <div class="shop-list-item">
                    <div class="shop-list-item__icon">{{ order.shop.emoji }}</div>
                    <div>
                        <div class="shop-list-item__title">{{ order.shop.textName }}</div>
                        <div class="shop-list-item__category">Продукты</div>
                    </div>
                </div>
            </div>
            <div style="width:120px; flex-shrink: 0;">
                <a href="//{{ order.shop.link }}" class="form-button" style="flex-shrink: 0;">В каталог</a>
            </div>
        </div>

        <a href="{{ path("order-add-item", {id:order.id}) }}" class="box-layout">
            <div class="add-position-button" style="padding: 0;">
                <span class="add-position-button__text">Купить вместе</span>
                <span class="add-position-button__plus">+</span>
            </div>
        </a>

        {% for groupedOrderItems in order.getOrderItemsGroupedByUser(get_current_user()) %}
            <div>
                {% if groupedOrderItems.user.id == get_current_user().id and loop.first %}
                    <div class="micro-title">Ваш заказ</div>
                {% else %}
                    {% if (loop.index == 2) or (groupedOrderItems.user.id != get_current_user().id and loop.first) %}
                        <div class="micro-title">Другие заказы</div>
                    {% endif %}
                {% endif %}

                <div class="box-layout box-layout_dark">
                    {% set user = groupedOrderItems['user'] %}
                    {% set orderItems = groupedOrderItems['items'] %}
                    {% set sumPrice = groupedOrderItems['price'] %}

                    {% if loop.first %}
                        {% for orderItem in orderItems %}
                            <div class="box-layout box-layout_square">
                                <div class="order-product-item__title">
                                    <span title="Добавить себе"><img class="order-product-item__cart" src="/edit-3.svg" alt="Добавить себе"></span>
                                    <a target="_blank" href="//{{ orderItem.link }}" class="label-product-title">{{ orderItem.name }}</a>
                                </div>
                                <div class="order-product-item__footer">
                                    <div class="order-product-item__quantity-control">
                                        <div class="order-product-item__button">-</div>
                                        <div class="order-product-self-item__quantity">{{ orderItem.amount }}</div>
                                        <div class="order-product-item__button">+</div>
                                    </div>

                                    <div class="order-product-self-item__price">
                                        {{ orderItem.getPriceForOne }} ₽
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        {% for orderItem in orderItems %}
                            <div class="order-product-item box-layout box-layout_square">
                                <div class="order-product-item__title">
                                    <span title="Добавить себе"><img class="order-product-item__cart" src="/shopping-cart.svg" alt="Добавить себе"></span>
                                    <a target="_blank" href="//{{ orderItem.link }}" class="label-product-title">{{ orderItem.name }}</a>
                                </div>
                                <div class="order-product-item__quantity">{{ orderItem.amount }} x {{ orderItem.getPriceForOne }} ₽</div>
                            </div>
                        {% endfor %}
                    {% endif %}

                    {% if groupedOrderItems.user.id == get_current_user().id and loop.first %}
                        <a href="{{ path("order-add-item", {id:order.id}) }}" class="add-position-button">
                            <span class="add-position-button__text">Добавить</span>
                            <span class="add-position-button__plus">+</span>
                        </a>
                    {% endif %}

                    <div class="order-product-item__croud-price">Участие <b>{{ order.getParticipationPrice }} ₽</b></div>
                    <div class="bottom-product-item-price">
                        {% if groupedOrderItems.user.id == get_current_user().id and loop.first %}
                            <div></div>
                        {% else %}
                            <div class="order-status order-status_payment" style="display: inline-block;">Не оплачен</div>
                        {% endif %}
                        <div>Итог <b>{{ sumPrice + order.getParticipationPrice }} ₽</b></div>
                    </div>

                    {% if not loop.first %}
                        <div class="user-footer">
                            <a href="#" class="icon-block">
                                <img class="icon-block__avatar" src="{{ user.avatarUrl }}" alt="">
                                <div>
                                    <div class="user-name-text">{{ user.fio }}&nbsp;&nbsp;&nbsp; <span style="font-size: 12px; font-weight: bold;color:#F6DC2D">Написать</span></div>
                                    <div class="user-name-micro">Участник</div>
                                </div>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock body %}

src/templates/shop-list.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h2>Создание совместной доставки</h2>

    <br>

    <div class="filters-buttons">
        <div class="filters-buttons__item">Продукты</div>
        <div class="filters-buttons__item">Электроника</div>
        <div class="filters-buttons__item">Аптека</div>
    </div>

    <br>

    <div class="shop-list-grid">
        <a href="#" class="box-layout">
            <div class="shop-list-item">
                <div class="shop-list-item__icon shop-list-item__icon_plus">+</div>
                <div class="shop-list-item__title">Добавить магазин</div>
            </div>
        </a>
        {% for shop in shops %}
            <a class="box-layout" href="{{ path('new_order', {shopId: shop.id}) }}">
                <div class="shop-list-item">
                    <div class="shop-list-item__icon">{{ shop.emoji }}</div>
                    <div>
                        <div class="shop-list-item__title">{{ shop.textName }}</div>
                        <div class="shop-list-item__category">Продукты</div>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock body %}